// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone", "collections/quotes", "text!/javascript/templates/home.html"], function($, _, Backbone, QuotesCollection, HomeTemplate) {
    var HomeView;
    return HomeView = Backbone.View.extend({
      el: "#main",
      template: _.template(HomeTemplate),
      initialize: function(options) {
        console.log("../models/quote");
        this.quotes_collection = new QuotesCollection();
        return this.quotes_collection.fetch();
      },
      render: function() {
        return $(this.el).html(this.template);
      }
    });
  });

}).call(this);
