// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone", "views/login", "text!/javascript/templates/home.html"], function($, _, Backbone, LoginView, HeaderTemplate) {
    var HomeView;
    return HomeView = Backbone.View.extend({
      el: "#main",
      template: _.template(HeaderTemplate),
      initialize: function(options) {
        return this.login_view = new LoginView();
      },
      render: function() {
        return $(this.el).html(this.template);
      }
    });
  });

}).call(this);
