// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone", "text!/javascript/templates/home.html"], function($, _, Backbone, HomeTemplate) {
    var HomeView;
    return HomeView = Backbone.View.extend({
      el: "#main",
      template: _.template(HomeTemplate),
      initialize: function(options) {
        this.collection = options.collection;
        return this.collection.bind("reset", this.render, this);
      },
      render: function() {
        console.log(this.collection);
        return $(this.el).html(this.template);
      }
    });
  });

}).call(this);
