// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
    var LoginView;
    return LoginView = Backbone.View.extend({
      initialize: function(options) {
        return console.log("Init login view");
      },
      render: function() {
        return console.log("Render login view");
      }
    });
  });

}).call(this);
