// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    paths: {
      jquery: "lib/jquery/jquery-min",
      underscore: "lib/underscore/underscore-min",
      backbone: "lib/backbone/backbone-min"
    },
    shim: {
      jquery_carousel: {
        deps: ["jquery"]
      },
      backbone: {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      underscore: {
        exports: "_"
      }
    }
  });

  define(["jquery", "router"], function($, Router) {
    return Router.initialize();
  });

}).call(this);
