// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone", "views/home"], function($, _, Backbone, HomeView) {
    var AppRouter;
    AppRouter = Backbone.Router.extend({
      routes: {
        "home": "home",
        "test": "test"
      },
      home: function() {
        var home_view;
        home_view = new HomeView();
        return home_view.render();
      },
      test: function() {
        return console.log("test");
      }
    });
    return {
      initialize: function() {
        var app_router;
        app_router = new AppRouter();
        return Backbone.history.start();
      }
    };
  });

}).call(this);
