// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone", "collections/quotes", "views/home"], function($, _, Backbone, QuotesCollection, HomeView) {
    var AppRouter;
    AppRouter = Backbone.Router.extend({
      routes: {
        "home": "home",
        "test": "test"
      },
      home: function() {
        var home_view, quotes_collection;
        quotes_collection = new QuotesCollection();
        quotes_collection.fetch();
        return home_view = new HomeView({
          collection: quotes_collection
        });
      },
      test: function() {
        return console.log("test");
      }
    });
    return {
      initialize: function() {
        var app_router;
        app_router = new AppRouter();
        return Backbone.history.start();
      }
    };
  });

}).call(this);
