// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
    var QuoteModel;
    QuoteModel = Backbone.Model.extend({
      defaults: {
        rating: 0
      },
      initialize: function() {}
    });
    return QuoteModel;
  });

}).call(this);
